### ISSUE TITLE
 lobe UI 提示詞分類選擇的風格問題

### ISSUE THREAD

**Issue by RadStorm04** [thisjam/sd-webui-oldsix-prompt#1]
小問題，在 lobe UI 裡提示詞分類選擇的風格有沒有可能從現在的分頁式改回最一開始的按鈕式? 私心覺得比較順眼

**Comment by thisjam** [comment]
不太懂你说上面  调下lobe的配置 试试

**Comment by RadStorm04** [comment]
![image](https://github.com/thisjam/sd-webui-oldsix-prompt/assets/2616683/57a32cc5-e469-464a-bdbc-cda0ea3d20d0)

**Comment by thisjam** [comment]
分类太多摆不下了，自然会变成两行，兄弟你的强迫症好厉害，下个版本我应该会减少分类，删除一些不必要的。

**Comment by RadStorm04** [comment]
不不不，我想表達的意思是分類的顯示"風格"，現在的分類風格是像網頁的分頁一樣

圖例:
![image](https://github.com/thisjam/sd-webui-oldsix-prompt/assets/2616683/a9254fe4-3593-4fa5-8197-a51019b1813a)

跟1.0版的按鈕風格明顯不一樣，抱歉好像顯得有點鑽牛角尖，我的表達能力不是很好
