### ISSUE TITLE
提示词分类是乱序？不是按01 02 03 这样排列，而是完全的乱序

### ISSUE THREAD

**Issue by firelife2008** [thisjam/sd-webui-oldsix-prompt#16]
提示词分类是乱序？不是按01 02 03 这样排列，而是完全的乱序
有点影响使用 问题不大 就是看着很不舒服
请问这是怎么回事呢？

**Comment by thisjam** [comment]
什么系统

**Comment by thisjam** [comment]
来群里吧，我看能不能帮你解决。

**Comment by firelife2008** [comment]
全部删了仓库重新下载就好了 可能之前直接拷贝的文件哪里有问题

**Comment by ertcds** [comment]
> 全部删了仓库重新下载就好了 可能之前直接拷贝的文件哪里有问题

我的也是mac，删除了extensions文件夹下的文件，重新还是不行

**Comment by ertcds** [comment]
![截屏2023-09-19 11.14.13.png](https://s1.locimg.com/2023/09/19/86e7ca9668352.png)
