### ISSUE TITLE
分享一下动态抽取提示词功能和dynamic-prompts插件的联动

### ISSUE THREAD

**Issue by Bobo-1125** [thisjam/sd-webui-oldsix-prompt#21]
在之前的版本里，我在本地把词库同步到了dynamic-prompts里，大概的做了一点内容，使用体验还蛮不错的，但一直没拉代码，回到github上想要分享时，才发现作者大大也做了动态抽取提示词的功能，但还是忍不住提个issues，两个插件结合到一起实在是太好用了

![image](https://github.com/thisjam/sd-webui-oldsix-prompt/assets/56570983/edf17954-8c39-4b4b-8744-7877f40c38a2)
![image](https://github.com/thisjam/sd-webui-oldsix-prompt/assets/56570983/73e9e3e8-7822-49c2-ac21-905a9bdf2dad)
![image](https://github.com/thisjam/sd-webui-oldsix-prompt/assets/56570983/f9e83a90-40d0-46fc-a08f-c1964c4992ed)

在动态抽取提示词的功能上，最终效果是一致的，不过语法上有差异，dynamic-prompts目前也更完善一点，其次wildcards做词库管理，可以直接用提示词补全插件进行快速的查询，整个编辑动态提示词的过程就再次聚焦到了提示词输入框里，缺点就是需要多装一个插件，如果还要tag补全的话，就是两个插件，emmmm....大概就分享下这些内容

**Comment by thisjam** [comment]
dynamic-prompts 我确实没有用过，出动态动能，是为了一些兄弟方便配合这边的词库炼丹什么的。
他这看起来像是用|分割，如何是这样，官方语法自带的|语法会不会就被覆盖掉了。

**Comment by Bobo-1125** [comment]
dynamic-prompts在使用|分隔符的时候，是在外层添加了一个{}花括号的，官方语法自带的|语法我也是才了解，作为交替渲染时，官方语法是用[]中括号去包住的，语法是有差异的，并且验证了没冲突。如果|符号用在提示词矩阵脚本中，会优先以提示词矩阵的语法为准，动态提示词将会失效，因此不存在语法覆盖。

另外dynamic-prompts，不仅仅可以用|分割，还可以使用通配符去抽取对应文件中的提示词，语法是__xxxx__，然后还有很多变体，具体的贴在下方啦，不知道这套动态提示词对项目否有帮助，如果可以的话，我回头完善一下，提个pr作者大大看一下效果

https://github.com/adieyal/sd-dynamic-prompts/blob/main/docs/SYNTAX.md

**Comment by Gh20221205** [comment]
> dynamic-prompts在使用|分隔符的时候，是在外层添加了一个{}花括号的，官方语法自带的|语法我也是才了解，作为交替渲染时，官方语法是用[]中括号去包住的，语法是有差异的，并且验证了没冲突。如果|符号用在提示词矩阵脚本中，会优先以提示词矩阵的语法为准，动态提示词将会失效，因此不存在语法覆盖。
> 
> 另外dynamic-prompts，不仅仅可以用|分割，还可以使用通配符去抽取对应文件中的提示词，语法是__xxxx__，然后还有很多变体，具体的贴在下方啦，不知道这套动态提示词对项目否有帮助，如果可以的话，我回头完善一下，提个pr作者大大看一下效果
> 
> https://github.com/adieyal/sd-dynamic-prompts/blob/main/docs/SYNTAX.md

在我这里两者有冲突。之前一直用dynamic prompt，语法就是用两个下划线作为首尾召唤文本，{}花括号，以及|分隔符，这时如果在任何位置加入#[]这样的语法，原来的两个下划线的语法立刻失效，不能召唤文本了。在命令窗里也能看出来，两个下划线不再被理解。

**Comment by Bobo-1125** [comment]
恩呢，我的想法是添加一个开关去控制使用何种语法，并Fork了项目去解决了这个问题，[sd-webui-oldsix-prompt-dynamic](https://github.com/Bobo-1125/sd-webui-oldsix-prompt-dynamic)，但是发现这样的交互没法去适配更多的变体用法，没有变体用法的加持，两者没有区别，所以就不必再单独多出一个插件，增添项目的依赖负担了，等作者大大完善吧
