### ISSUE TITLE
默认不要弹出 输入中文后按回车翻译,[ALT]键呼出/隐藏

### ISSUE THREAD

**Issue by cenfun** [thisjam/sd-webui-oldsix-prompt#26]
![image](https://github.com/thisjam/sd-webui-oldsix-prompt/assets/334577/ce3b45d2-c4a1-4bcc-ade1-d38c83fe9511)
这个每次弹出来好烦，请支持不弹出这个，并不是每个人都需要这个，谢谢

**Comment by cenfun** [comment]
还要alt快捷键和图生图的图片放大冲突了

**Comment by S1U** [comment]
支持。默认行为就应该关闭，需要的话才用快捷键呼出。

**Comment by liulsg** [comment]
还好开启的的，太方便了。
