### ISSUE TITLE
提示词的整理者路过一下... ...

### ISSUE THREAD

**Issue by SingUnderStar** [thisjam/sd-webui-oldsix-prompt#3]
一是整理这些词不太容易，希望能标记提示词来自知乎“路过银河”
二是这个插件比我之前找的日本人的插件好用太多了，感谢作者的创作。

**Comment by thisjam** [comment]
> 一是整理这些词不太容易，希望能标记提示词来自知乎“路过银河” 二是这个插件比我之前找的日本人的插件好用太多了，感谢作者的创作。

是你本人吗？太感谢了，可以来我群里面吗大佬，有没有这个荣幸。

**Comment by SingUnderStar** [comment]
> > 一是整理这些词不太容易，希望能标记提示词来自知乎“路过银河” 二是这个插件比我之前找的日本人的插件好用太多了，感谢作者的创作。
> 
> 是你本人吗？太感谢了，可以来我群里面吗大佬，有没有这个荣幸。

不太用QQ了，有微信群嘛（捂脸）

**Comment by henbucuoshanghai** [comment]
微信群？

**Comment by henbucuoshanghai** [comment]
整理了一些关键词？能加进去？
