### ISSUE TITLE
提示词框都不显示,太差了

### ISSUE THREAD

**Issue by OEIEE** [thisjam/sd-webui-oldsix-prompt#34]
发送到提示词框之下提示词直接不显示,发送到提示词框功能也无效,只有随机词能出来,其它全废,
多个版本多个浏览器测试一样,太差了,直接删除.
SD1.5.2

**Comment by thisjam** [comment]
> 发送到提示词框之下提示词直接不显示,发送到提示词框功能也无效,只有随机词能出来,其它全废, 多个版本多个浏览器测试一样,太差了,直接删除. SD1.5.2

你的环境坏了，玩SD控制台从来都不看的吗？

**Comment by wyjzp** [comment]
菜，就多练

**Comment by cai567890** [comment]
alt+Q呼出翻译框无效了，没有其他操作代替吗？
