### ISSUE TITLE
垃圾群，必须按照下载他插件使用才行，不然呗秒踢出群聊

### ISSUE THREAD

**Issue by hackdiqi** [thisjam/sd-webui-oldsix-prompt#41]
字面上完全写着AI交流群，我就说我没安装这个插件直接给踢出去了，垃圾群，建立尼玛个逼群，鑫鑫管理员垃圾一个

**Comment by hackdiqi** [comment]
进群只是AI交流目的，进群还非得要求安装插件，你没发现你的插件写的很垃圾吗，垃圾插件谁安装？AI交流群你不如说是插件用户交流群，省的颠倒是非

**Comment by aimarxjg** [comment]
哈哈哈 是的 还看不起秋叶整合包，脑残

**Comment by aimarxjg** [comment]
哈哈哈是的
