### ISSUE TITLE
插件好像和最新的SD webui 1.90不兼容

### ISSUE THREAD

**Issue by seraphdoo** [thisjam/sd-webui-oldsix-prompt#48]
插件在SD webui 1.90下无法显示。希望开发者关注一下。

**Comment by thisjam** [comment]
> 插件在SD webui 1.90下无法显示。希望开发者关注一下。
具体哪里

**Comment by ogun106** [comment]
插件版本回退到2023.10.27的版本就可以显示了。

**Comment by 1kFace8aby** [comment]
能显示 左下角有个六字的圆圈 但点进去就退不出来了
