### ISSUE TITLE
提示词选项没出现

### ISSUE THREAD

**Issue by Fang344** [thisjam/sd-webui-oldsix-prompt#5]
![ss](https://github.com/thisjam/sd-webui-oldsix-prompt/assets/136895446/046e01c4-d8ba-447b-bc0e-a5a4f8ee1451)
是不是少了什么？选项全部没出现

**Comment by thisjam** [comment]
升级你的webui   可能版本太低

**Comment by FlyMao028** [comment]
同样的问题，没找到解决办法

**Comment by IM515BT** [comment]
用的秋叶整合吧本体切换到151就看见了

**Comment by Fang344** [comment]
> 升级你的webui 可能版本太低

升级了webui，提示词出现了，谢谢👍
