### ISSUE TITLE
可以给菜单添加一个ESC按钮吗

### ISSUE THREAD

**Issue by 1kFace8aby** [thisjam/sd-webui-oldsix-prompt#50]
有时候用colab和本地监听在iPad上用的时候那个球点进去就退不出来了

**Comment by thisjam** [comment]
> 有时候用colab和本地监听在iPad上用的时候那个球点进去就退不出来了

在PC上ESC按键可以推出，升级一下，现在添加了右上角关闭按钮

**Comment by 1kFace8aby** [comment]
> > 有时候用colab和本地监听在iPad上用的时候那个球点进去就退不出来了
> 
> 在PC上ESC按键可以推出，升级一下，现在添加了右上角关闭按钮

nice 兄弟
