### ISSUE TITLE
求解大佬 没有提示词的选项，只有随机的选项。

### ISSUE THREAD

**Issue by 20070949pop** [thisjam/sd-webui-oldsix-prompt#7]
![image](https://github.com/thisjam/sd-webui-oldsix-prompt/assets/76022928/952cf1ab-9c21-4b82-b29f-45c48ffc7042)

**Comment by 20070949pop** [comment]
烦请大佬看看，感谢大佬的超牛插件。

**Comment by thisjam** [comment]
升级webui版本

**Comment by 20070949pop** [comment]
感谢大佬 已经可用

**Comment by xingyu217** [comment]
已经是最新的，v1.5.1， 还是只有随机灵感，什么原因

**Comment by thisjam** [comment]
> 已经是最新的，v1.5.1， 还是只有随机灵感，什么原因

电脑什么配置，什么系统，是否是固态硬盘

**Comment by Dean8998** [comment]
同问，版本1.5.2，windows, 固态硬盘

**Comment by fanrenshijue** [comment]
大佬，MAC系统，也是只有随机的选项，没有提示词

**Comment by RockyFong** [comment]
mac系統 最新的webui, 也有這個問題

**Comment by RockyFong** [comment]
> mac系統 最新的webui, 也有這個問題
解決了, 需要在環境下安裝basicsr.
